### ISSUE TITLE
llvm checkout not working

### ISSUE THREAD

**Issue by flynn1973** [shawnanastasio/chromium_power#3]
i followed the steps in the wiki, but failed at the llvm checkout step...

root@lpgaixmgmtlx01:/scratch/chromium_build>svn checkout --force https://llvm.org/svn/llvm-project/llvm/trunk@$CLANG_SVN_REVISION llvm
svn: E170000: URL 'https://llvm.org/svn/llvm-project/llvm/trunk@n340759' doesn't exist

is the wiki outdated or what is the problem here? i heard they switched to github anyway.

**Comment by flynn1973** [comment]
i used the redhat llvm-toolset until i get something back here...

root@lpgaixmgmtlx01:/scratch/chromium_build/chromium_power>clang --version
clang version 8.0.1 (Red Hat 8.0.1-8.el7)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rh/llvm-toolset-8.0/root/usr/bin

**Comment by llebout** [comment]
I recommend referring to this: https://gitlab.com/chromium-ppc64le/chromium-ppc64le

**Comment by flynn1973** [comment]
this does not run on redhat..glibc to old.

root@lpgaixmgmtlx01:/root/chromium-browser-stable-79.0.3945.130-1>./chrome
./chrome: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./chrome)
./chrome: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./chrome)
./chrome: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./chrome)

**Comment by llebout** [comment]
@flynn1973 I meant that the build process there works and it should guide you to success.

**Comment by flynn1973** [comment]
ah ok,  meanwhile i cloned llvm from github and the master branch contains the right version for the chrome build.
